Extend commands options master
rhevm-qe-automation/python-rrmngmnt pull request #132
Opened 2020-11-04 15:04 UTC by MosheSheena

2020-11-04 15:14 UTC, myakove requested changes
This PR should be split into 3 PRs.
1, python version chnges.
2. Format strings.
3. introduce _type_options_builder

2020-11-04 15:14 UTC, myakove commented on .gitignore
> +/.venv/
How this is related to this PR?

2020-11-04 15:14 UTC, myakove commented on .travis.yml
> +- '3.7'
ditto

2020-11-04 15:14 UTC, myakove commented on rrmngmnt/nmcli.py
> +        **kwargs
kwargs hide a lot of things, any reason to use it and not specify the args that you need here?

2020-11-04 15:14 UTC, myakove commented on rrmngmnt/nmcli.py
> +            *args: positional arguments.
where do you get args here?

2020-11-04 15:14 UTC, myakove commented on rrmngmnt/nmcli.py
> +            **kwargs: keyword arguments.
**kwargs: keyword arguments. is not the way to write a docstring.
please specify what are the kwargs expected here.

2020-11-04 15:14 UTC, myakove commented on setup.cfg
> +    Programming Language :: Python :: 3.7
not related to this PR

2020-11-04 15:14 UTC, myakove commented on tox.ini
> +envlist = py36,py37,pep8
ditto

2020-11-04 15:14 UTC, myakove commented on tox.ini
> +3.7 = py37, pep8
ditto

2020-11-05 11:26 UTC, MosheSheena commented
> This PR should be split into 3 PRs.
> 1, python version chnges.
> 2. Format strings.
> 3. introduce _type_options_builder

I thought I could split it into several commits instead of multiple PRs, but I'm fine with splitting it.
How can I preserve all your comments if I drop this PR and start over?

2020-11-10 12:44 UTC, closed without merging